sudo: false
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
language: groovy
jdk:
  - oraclejdk8
script:
  - ./gradlew check --no-daemon
after_success:
- ./gradlew coveralls